# Utiliser l'image PostgreSQL
FROM postgres:12

# Définir les variables d'environnement
ENV POSTGRES_DB=dbname
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password

# (Optionnel) Exécuter des scripts SQL ou des commandes shell qui personnalisent votre base de données
# COPY ./init.sql /docker-entrypoint-initdb.d/
